version: '1.0'

services:
  imageinator:
    image: imageinator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    restart: unless-stopped